/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class Connector (
  /* Connector ID number */
  id: Int,
  /* Connector lowercase system name */
  name: String,
  /* Connector pretty display name */
  displayName: String,
  /* URL to the image of the connector logo */
  image: String,
  /* URL to a site where one can get this device or application */
  getItUrl: String,
  /* True if the authenticated user has this connector enabled */
  connected: String,
  /* URL and parameters used when connecting to a service */
  connectInstructions: String,
  /* Epoch timestamp of last sync */
  lastUpdate: Int,
  /* Number of measurements obtained during latest update */
  totalMeasurementsInLastUpdate: Int,
  /* True if user has no measurements for this connector */
  noDataYet: Boolean)
   extends ApiModel


