/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class ConnectorInfoHistoryItem (
  /* Number of measurements */
  numberOfMeasurements: Int,
  /* True if the update was successfull */
  success: Boolean,
  /* Error message. */
  message: String,
  /* Date and time of the update in UTC time zone */
  createdAt: String)
   extends ApiModel


