/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class ConnectorInfo (
  /* Connector ID number */
  id: Int,
  /* True if the authenticated user has this connector enabled */
  connected: Boolean,
  /* Error message. Empty if connected. */
  error: String,
  history: Seq[ConnectorInfoHistoryItem])
   extends ApiModel


