/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class ConversionStep (
  /* ADD or MULTIPLY */
  operation: ConversionStepEnums.Operation,
  /* This specifies the order of conversion steps starting with 0 */
  value: Double)
   extends ApiModel

object ConversionStepEnums {

  type Operation = Operation.Value
  
  object Operation extends Enumeration {
    val MULTIPLY = Value("MULTIPLY")
    val ADD = Value("ADD")
  }

  
}

