/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class Credential (
  /* ID of user that owns this credential */
  userId: Option[Int],
  /* The id for the connector data source from which the credential was obtained */
  connectorId: Int,
  /* Attribute name such as token, userid, username, or password */
  attrKey: String,
  /* Encrypted value for the attribute specified */
  attrValue: String,
  /* When the record was first created. Use ISO 8601 datetime format */
  createdAt: Option[DateTime],
  /* When the record in the database was last updated. Use ISO 8601 datetime format */
  updatedAt: Option[DateTime])
   extends ApiModel


