/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class Measurement (
  /* ORIGINAL Name of the variable for which we are creating the measurement records */
  variable: String,
  /* Application or device used to record the measurement values */
  source: String,
  /* Start Time for the measurement event in ISO 8601 */
  startTime: String,
  /* Start Time for the measurement event in ISO 8601 */
  humanTime: Option[HumanTime],
  /* Converted measurement value in requested unit */
  value: Double,
  /* Unit of measurement as requested in GET request */
  unit: String,
  /* Original value */
  originalValue: Option[Int],
  /* Measurement value in the unit as orignally submitted */
  storedValue: Option[Double],
  /* Unit of measurement as originally submitted */
  storedAbbreviatedUnitName: Option[String],
  /* Original Unit of measurement as originally submitted */
  originalAbbreviatedUnitName: Option[String],
  /* Unit of measurement as originally submitted */
  abbreviatedUnitName: Option[String],
  /* Note of measurement */
  note: Option[String])
   extends ApiModel


