/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class PostVote (
  /* Cause variable name */
  cause: String,
  /* Effect variable name */
  effect: String,
  /* Vote: 0 (for implausible) or 1 (for plausible) */
  vote: Boolean)
   extends ApiModel


