/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class TrackingReminderNotification (
  /* id for the specific PENDING tracking remidner */
  id: Int,
  /* id for the repeating tracking remidner */
  trackingReminderId: Int,
  /* clientId */
  clientId: Option[String],
  /* ID of User */
  userId: Option[Int],
  /* Id for the variable to be tracked */
  variableId: Option[Int],
  /* ISO 8601 timestamp for the specific time the variable should be tracked in UTC.  This will be used for the measurement startTime if the track endpoint is used. */
  pendingReminderTime: Option[DateTime],
  /* Default value to use for the measurement when tracking */
  defaultValue: Option[Float],
  /* String identifier for the sound to accompany the reminder */
  reminderSound: Option[String],
  /* True if the reminders should appear as a popup notification */
  popUp: Option[Boolean],
  /* True if the reminders should be delivered via SMS */
  sms: Option[Boolean],
  /* True if the reminders should be delivered via email */
  email: Option[Boolean],
  /* True if the reminders should appear in the notification bar */
  notificationBar: Option[Boolean],
  /* When the record in the database was last updated. Use ISO 8601 datetime format. Time zone should be UTC and not local. */
  updatedAt: Option[DateTime],
  /* Name of the variable to be used when sending measurements */
  variableName: Option[String],
  /* Name of the variable category to be used when sending measurements */
  variableCategoryName: Option[String],
  /* Abbreviated name of the unit to be used when sending measurements */
  abbreviatedUnitName: Option[String],
  /* The way multiple measurements are aggregated over time */
  combinationOperation: Option[TrackingReminderNotificationEnums.CombinationOperation])
   extends ApiModel

object TrackingReminderNotificationEnums {

  type CombinationOperation = CombinationOperation.Value
  
  object CombinationOperation extends Enumeration {
    val MEAN = Value("MEAN")
    val SUM = Value("SUM")
  }

  
}

