/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class Update (
  /* id */
  id: Option[Int],
  /* user_id */
  userId: Int,
  /* connector_id */
  connectorId: Int,
  /* number_of_measurements */
  numberOfMeasurements: Int,
  /* success */
  success: Boolean,
  /* message */
  message: String,
  /* When the record was first created. Use ISO 8601 datetime format */
  createdAt: Option[DateTime],
  /* When the record in the database was last updated. Use ISO 8601 datetime format */
  updatedAt: Option[DateTime])
   extends ApiModel


