/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class UserVariableRelationship (
  /* id */
  id: Option[Int],
  /* Our confidence that a consistent predictive relationship exists based on the amount of evidence, reproducibility, and other factors */
  confidenceLevel: String,
  /* A quantitative representation of our confidence that a consistent predictive relationship exists based on the amount of evidence, reproducibility, and other factors */
  confidenceScore: Float,
  /* Direction is positive if higher predictor values generally precede higher outcome values. Direction is negative if higher predictor values generally precede lower outcome values. */
  direction: String,
  /* Number of seconds over which the predictor variable event is expected to produce a perceivable effect following the onset delay */
  durationOfAction: Int,
  /* error_message */
  errorMessage: Option[String],
  /* User estimated (or default number of seconds) after cause measurement before a perceivable effect is observed */
  onsetDelay: Option[Int],
  /* Variable ID for the outcome variable */
  outcomeVariableId: Int,
  /* Variable ID for the predictor variable */
  predictorVariableId: Int,
  /* ID for default unit of the predictor variable */
  predictorUnitId: Int,
  /* A value representative of the relevance of this predictor relative to other predictors of this outcome.  Usually used for relevancy sorting. */
  sinnRank: Float,
  /* Can be weak, medium, or strong based on the size of the effect which the predictor appears to have on the outcome relative to other variable relationship strength scores. */
  strengthLevel: String,
  /* A value represented to the size of the effect which the predictor appears to have on the outcome. */
  strengthScore: Float,
  /* user_id */
  userId: Option[Int],
  /* vote */
  vote: Option[String],
  /* Value for the predictor variable (in it's default unit) which typically precedes an above average outcome value */
  valuePredictingHighOutcome: Float,
  /* Value for the predictor variable (in it's default unit) which typically precedes a below average outcome value */
  valuePredictingLowOutcome: Float)
   extends ApiModel


