/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class UserTag (
  /* This is the id of the variable being tagged with an ingredient or something. */
  taggedVariableId: Int,
  /* This is the id of the ingredient variable whose value is determined based on the value of the tagged variable. */
  tagVariableId: Int,
  /* Number by which we multiply the tagged variable value to obtain the tag variable (ingredient) value */
  conversionFactor: Double)
   extends ApiModel


