/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class UserVariables (
  /* User ID */
  user: Int,
  /* Common variable id */
  variableId: Int,
  /* Estimated duration of time following the onset delay in which a stimulus produces a perceivable effect */
  durationOfAction: Option[Int],
  /* fillingValue */
  fillingValue: Option[Int],
  /* joinWith */
  joinWith: Option[String],
  /* maximumAllowedValue */
  maximumAllowedValue: Option[Float],
  /* minimumAllowedValue */
  minimumAllowedValue: Option[Float],
  /* onsetDelay */
  onsetDelay: Option[Int],
  /* Earliest measurement startTime that should be used in analysis in ISO format */
  experimentStartTime: Option[String],
  /* Latest measurement startTime that should be used in analysis in ISO format */
  experimentEndTime: Option[String])
   extends ApiModel


