/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime


case class Variable (
  /* Variable ID */
  id: Option[Int],
  /* User-defined variable display name. */
  name: String,
  /* Name used when the variable was originally created in the `variables` table. */
  originalName: String,
  /* Variable category like Mood, Sleep, Physical Activity, Treatment, Symptom, etc. */
  category: String,
  /* Abbreviated name of the default unit for the variable */
  abbreviatedUnitName: String,
  /* Id of the default unit for the variable */
  abbreviatedUnitId: Int,
  /* Comma-separated list of source names to limit variables to those sources */
  sources: String,
  /* Minimum reasonable value for this variable (uses default unit) */
  minimumValue: Double,
  /* Maximum reasonable value for this variable (uses default unit) */
  maximumValue: Double,
  /* Way to aggregate measurements over time. Options are \"MEAN\" or \"SUM\".  SUM should be used for things like minutes of exercise.  If you use MEAN for exercise, then a person might exercise more minutes in one day but add separate measurements that were smaller.  So when we are doing correlational analysis, we would think that the person exercised less that day even though they exercised more.  Conversely, we must use MEAN for things such as ratings which cannot be SUMMED. */
  combinationOperation: VariableEnums.CombinationOperation,
  /* Value for replacing null measurements */
  fillingValue: Double,
  /* The Variable this Variable should be joined with. If the variable is joined with some other variable then it is not shown to user in the list of variables. */
  joinWith: String,
  /* Array of Variables that are joined with this Variable */
  joinedVariables: Seq[Variable],
  /* Id of the parent variable if this variable has any parent */
  parent: Int,
  /* Array of Variables that are sub variables to this Variable */
  subVariables: Seq[Variable],
  /* How long it takes for a measurement in this variable to take effect */
  onsetDelay: Int,
  /* How long the effect of a measurement in this variable lasts */
  durationOfAction: Int,
  /* Earliest measurement time */
  earliestMeasurementTime: Int,
  /* Latest measurement time */
  latestMeasurementTime: Int,
  /* When this variable or its settings were last updated */
  updated: Int,
  /* A value of 1 indicates that this variable is generally a cause in a causal relationship.  An example of a causeOnly variable would be a variable such as Cloud Cover which would generally not be influenced by the behaviour of the user. */
  causeOnly: Int,
  /* Number of correlations */
  numberOfCorrelations: Int,
  /* Outcome variables (those with `outcome` == 1) are variables for which a human would generally want to identify the influencing factors.  These include symptoms of illness, physique, mood, cognitive performance, etc.  Generally correlation calculations are only performed on outcome variables. */
  outcome: Int,
  /* The number of measurements that a given user had for this variable the last time a correlation calculation was performed. Generally correlation values are only updated once the current number of measurements for a variable is more than 10% greater than the measurementsAtLastAnalysis.  This avoids a computationally-demanding recalculation when there's not enough new data to make a significant difference in the correlation. */
  measurementsAtLastAnalysis: Int,
  /* Number of measurements */
  numberOfMeasurements: Int,
  /* Last unit */
  lastUnit: String,
  /* Last value */
  lastValue: Int,
  /* Most common value */
  mostCommonValue: Int,
  /* Most common unit */
  mostCommonUnit: String,
  /* Last source */
  lastSource: Int)
   extends ApiModel

object VariableEnums {

  type CombinationOperation = CombinationOperation.Value
  
  object CombinationOperation extends Enumeration {
    val MEAN = Value("MEAN")
    val SUM = Value("SUM")
  }

  
}

